version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: install hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - run:
          name: lint
          command: |
            make build-lint-pom
            make lint-docker
      - persist_to_workspace:
          root: ~/
          paths:
            - project/
  test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: run spring boot test
          command: |
            make run-test

  push-image:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/dock
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: push docker image 
          command: |
            echo "hello"


  go-live:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar gzip
          command: |
            yum install -y tar gzip
      - run:
          name: Install eksctl
          command: |
            echo "hello"
      - run:
          name: Deploy using eksctl, kubectl
          command: |
            echo "hello"

  update:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar gzip
          command: |
            yum install -y tar gzip
      - run:
          name: update deploy
          command: |
            echo "hello"

workflows:
  default:
    jobs:
      - lint     
      - test:
          requires: [lint]
      - push-image
      - go-live:
          requires: [push-image]
      - update:
          requires: [go-live]    